name: Ada_Caser

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:

  build:
    name: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false # Attempt to generate as many of them as possible
      matrix:
        os:
          - macos-13
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: alire-project/setup-alire@v4
      - if: {{ matrix.windows-latest }}
        run: alr settings --set dependencies.shared false
      - run: alr build -- -gnatwJ
      - if: {{ ! matrix.windows-latest }}
        run: bin/ada_caser --version
      - if: {{ matrix.windows-latest }}
        run: bin\ada_caser --version
